// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUjhkoGUc0NxTcnJMfwQGOQ0AzWvMYpdk',
    appId: '1:1079259497366:web:ea69cafb314b332b1d93b7',
    messagingSenderId: '1079259497366',
    projectId: 'roadmate-01',
    authDomain: 'roadmate-01.firebaseapp.com',
    storageBucket: 'roadmate-01.firebasestorage.app',
    measurementId: 'G-4WFX5MEPPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_wasruS4190W1IqrN7t0XmiaTDweywr4',
    appId: '1:1079259497366:android:2524af3041b4a53c1d93b7',
    messagingSenderId: '1079259497366',
    projectId: 'roadmate-01',
    storageBucket: 'roadmate-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0rjcrG8WRj6penspl5ZgteXw9-UVRlg',
    appId: '1:1079259497366:ios:86c11700ea5551431d93b7',
    messagingSenderId: '1079259497366',
    projectId: 'roadmate-01',
    storageBucket: 'roadmate-01.firebasestorage.app',
    iosBundleId: 'com.example.roadMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa0rjcrG8WRj6penspl5ZgteXw9-UVRlg',
    appId: '1:1079259497366:ios:86c11700ea5551431d93b7',
    messagingSenderId: '1079259497366',
    projectId: 'roadmate-01',
    storageBucket: 'roadmate-01.firebasestorage.app',
    iosBundleId: 'com.example.roadMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUjhkoGUc0NxTcnJMfwQGOQ0AzWvMYpdk',
    appId: '1:1079259497366:web:c87342e7aae6d1641d93b7',
    messagingSenderId: '1079259497366',
    projectId: 'roadmate-01',
    authDomain: 'roadmate-01.firebaseapp.com',
    storageBucket: 'roadmate-01.firebasestorage.app',
    measurementId: 'G-3R8PCMWJ3E',
  );
}
